[site]
name = "Linotype"
style = "linotype"
icon = "favicon.ico"

[menu]
names = [
    "Home",
    "About",
    "Mechanics",
    "Control",
    "Estimation",
    "Optimization",
    "Reading List",
    "Contact",
]
links = [
    "/",
    "/about",
    "/v1.0.0/mechanics",
    "/v1.0.0/control",
    "/v1.0.0/estimation",
    "/v1.0.0/optimization",
    "/reading-list",
    "/contact",
]

[analytics]
tag = "analytics.html"

[media]
include = [

]
