[site]
name = "Linotype"
style = "linotype"
icon = "favicon.ico"

[menu]
names = [
    "Home",
    "About",
    "Optimization",
    "Stochastic Processes",
    "Contact",
]
links = [
    "/",
    "/about",
    "/v0.1.0/optimization",
    "/v0.1.0/stochastic-processes",
    "/contact",
]

[media]
include = [

]
