[site]
name = "Linotype"
style = "linotype"
icon = "favicon.ico"

[menu]
names = [
    "Home",
    "About",
    "Optimization",
    "Stochastic Processes",
    "Contact",
]
links = [
    "/",
    "/about",
    "/optimization",
    "/stochastic-processes",
    "/contact",
]

[media]
include = [
    "fokker-planck-equation.bib",
    "karush-kuhn-tucker.bib",
    "primal-dual-interior-point-method.bib",
]
